2024-12-10 21:02:30,833 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\marus\PythonProject\homework\Двеннадцатый модуль\modul_12_4.py", line 20, in test_run
    a = Runner(name=54, speed=10)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marus\PythonProject\homework\Двеннадцатый модуль\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-10 21:02:30,838 | ERROR | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\marus\PythonProject\homework\Двеннадцатый модуль\modul_12_4.py", line 10, in test_walk
    a = Runner('name', speed=-5)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marus\PythonProject\homework\Двеннадцатый модуль\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
